/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FindingMatchesRouteImport } from './routes/finding-matches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as DiscoverIndexRouteImport } from './routes/discover.index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as OnboardingVerificationRouteImport } from './routes/onboarding.verification'
import { Route as OnboardingQuizRouteImport } from './routes/onboarding.quiz'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding.profile'
import { Route as OnboardingPreferencesRouteImport } from './routes/onboarding.preferences'
import { Route as OnboardingHousingRouteImport } from './routes/onboarding.housing'
import { Route as DiscoverFilterRouteImport } from './routes/discover.filter'
import { Route as CompatibilityIdRouteImport } from './routes/compatibility.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingMatchesRoute = FindingMatchesRouteImport.update({
  id: '/finding-matches',
  path: '/finding-matches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingVerificationRoute = OnboardingVerificationRouteImport.update({
  id: '/onboarding/verification',
  path: '/onboarding/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingQuizRoute = OnboardingQuizRouteImport.update({
  id: '/onboarding/quiz',
  path: '/onboarding/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/onboarding/profile',
  path: '/onboarding/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPreferencesRoute = OnboardingPreferencesRouteImport.update({
  id: '/onboarding/preferences',
  path: '/onboarding/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingHousingRoute = OnboardingHousingRouteImport.update({
  id: '/onboarding/housing',
  path: '/onboarding/housing',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverFilterRoute = DiscoverFilterRouteImport.update({
  id: '/discover/filter',
  path: '/discover/filter',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilityIdRoute = CompatibilityIdRouteImport.update({
  id: '/compatibility/$id',
  path: '/compatibility/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finding-matches': typeof FindingMatchesRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/otp': typeof OtpRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/chat/$id': typeof ChatIdRoute
  '/compatibility/$id': typeof CompatibilityIdRoute
  '/discover/filter': typeof DiscoverFilterRoute
  '/onboarding/housing': typeof OnboardingHousingRoute
  '/onboarding/preferences': typeof OnboardingPreferencesRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/quiz': typeof OnboardingQuizRoute
  '/onboarding/verification': typeof OnboardingVerificationRoute
  '/profile/$id': typeof ProfileIdRoute
  '/chat/': typeof ChatIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finding-matches': typeof FindingMatchesRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/otp': typeof OtpRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/chat/$id': typeof ChatIdRoute
  '/compatibility/$id': typeof CompatibilityIdRoute
  '/discover/filter': typeof DiscoverFilterRoute
  '/onboarding/housing': typeof OnboardingHousingRoute
  '/onboarding/preferences': typeof OnboardingPreferencesRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/quiz': typeof OnboardingQuizRoute
  '/onboarding/verification': typeof OnboardingVerificationRoute
  '/profile/$id': typeof ProfileIdRoute
  '/chat': typeof ChatIndexRoute
  '/discover': typeof DiscoverIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finding-matches': typeof FindingMatchesRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/otp': typeof OtpRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/chat/$id': typeof ChatIdRoute
  '/compatibility/$id': typeof CompatibilityIdRoute
  '/discover/filter': typeof DiscoverFilterRoute
  '/onboarding/housing': typeof OnboardingHousingRoute
  '/onboarding/preferences': typeof OnboardingPreferencesRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/quiz': typeof OnboardingQuizRoute
  '/onboarding/verification': typeof OnboardingVerificationRoute
  '/profile/$id': typeof ProfileIdRoute
  '/chat/': typeof ChatIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finding-matches'
    | '/login'
    | '/matches'
    | '/otp'
    | '/safety'
    | '/settings'
    | '/signup'
    | '/chat/$id'
    | '/compatibility/$id'
    | '/discover/filter'
    | '/onboarding/housing'
    | '/onboarding/preferences'
    | '/onboarding/profile'
    | '/onboarding/quiz'
    | '/onboarding/verification'
    | '/profile/$id'
    | '/chat/'
    | '/discover/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finding-matches'
    | '/login'
    | '/matches'
    | '/otp'
    | '/safety'
    | '/settings'
    | '/signup'
    | '/chat/$id'
    | '/compatibility/$id'
    | '/discover/filter'
    | '/onboarding/housing'
    | '/onboarding/preferences'
    | '/onboarding/profile'
    | '/onboarding/quiz'
    | '/onboarding/verification'
    | '/profile/$id'
    | '/chat'
    | '/discover'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/finding-matches'
    | '/login'
    | '/matches'
    | '/otp'
    | '/safety'
    | '/settings'
    | '/signup'
    | '/chat/$id'
    | '/compatibility/$id'
    | '/discover/filter'
    | '/onboarding/housing'
    | '/onboarding/preferences'
    | '/onboarding/profile'
    | '/onboarding/quiz'
    | '/onboarding/verification'
    | '/profile/$id'
    | '/chat/'
    | '/discover/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FindingMatchesRoute: typeof FindingMatchesRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  OtpRoute: typeof OtpRoute
  SafetyRoute: typeof SafetyRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  ChatIdRoute: typeof ChatIdRoute
  CompatibilityIdRoute: typeof CompatibilityIdRoute
  DiscoverFilterRoute: typeof DiscoverFilterRoute
  OnboardingHousingRoute: typeof OnboardingHousingRoute
  OnboardingPreferencesRoute: typeof OnboardingPreferencesRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
  OnboardingQuizRoute: typeof OnboardingQuizRoute
  OnboardingVerificationRoute: typeof OnboardingVerificationRoute
  ProfileIdRoute: typeof ProfileIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  DiscoverIndexRoute: typeof DiscoverIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finding-matches': {
      id: '/finding-matches'
      path: '/finding-matches'
      fullPath: '/finding-matches'
      preLoaderRoute: typeof FindingMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/': {
      id: '/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/verification': {
      id: '/onboarding/verification'
      path: '/onboarding/verification'
      fullPath: '/onboarding/verification'
      preLoaderRoute: typeof OnboardingVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/quiz': {
      id: '/onboarding/quiz'
      path: '/onboarding/quiz'
      fullPath: '/onboarding/quiz'
      preLoaderRoute: typeof OnboardingQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/onboarding/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/preferences': {
      id: '/onboarding/preferences'
      path: '/onboarding/preferences'
      fullPath: '/onboarding/preferences'
      preLoaderRoute: typeof OnboardingPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/housing': {
      id: '/onboarding/housing'
      path: '/onboarding/housing'
      fullPath: '/onboarding/housing'
      preLoaderRoute: typeof OnboardingHousingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/filter': {
      id: '/discover/filter'
      path: '/discover/filter'
      fullPath: '/discover/filter'
      preLoaderRoute: typeof DiscoverFilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibility/$id': {
      id: '/compatibility/$id'
      path: '/compatibility/$id'
      fullPath: '/compatibility/$id'
      preLoaderRoute: typeof CompatibilityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindingMatchesRoute: FindingMatchesRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  OtpRoute: OtpRoute,
  SafetyRoute: SafetyRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  ChatIdRoute: ChatIdRoute,
  CompatibilityIdRoute: CompatibilityIdRoute,
  DiscoverFilterRoute: DiscoverFilterRoute,
  OnboardingHousingRoute: OnboardingHousingRoute,
  OnboardingPreferencesRoute: OnboardingPreferencesRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
  OnboardingQuizRoute: OnboardingQuizRoute,
  OnboardingVerificationRoute: OnboardingVerificationRoute,
  ProfileIdRoute: ProfileIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  DiscoverIndexRoute: DiscoverIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
